---
name: Taylor
surname: Dunn
#position: "Data Scientist"
address: "Halifax, Nova Scotia"
phone: 1 902 940 2210
www: tdunn.ca
email: "t.dunn19@gmail.com"
#twitter: TDunn12
headcolor: 779ECB
github: taylordunn
linkedin: dunn-taylor
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: false
    #show_footer: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(tibble)
library(knitr)
library(kableExtra)
```

\vspace{-5mm}

# Experience

```{r}
tribble(
  ~ year, ~ position, ~ company, ~ location, ~ details,
  "2017-", "Biostatistician", "Ardea Outcomes", "Halifax, NS",
  c("Worked on global clinical trials and real-world evidence studies in multiple disease areas. Duties included:
    \\begin{itemize}
      \\item Data management: reporting, transfers, database monitoring, queries.
      \\item Statistical analysis, interpretation, and presentation of results.
      \\item Study planning: protocols, statistical analysis plans, data management plans, literature reviews.
    \\end{itemize}",
    "Conducted patient-centric research, resulting in several peer-reviewed publications and presentations. Examples:
    \\begin{itemize}
      \\item Developed a machine learning model to predict patient dementia stage, achieving 83\\% balanced accuracy. (\\textcolor{tdunn-blue}{\\href{https://www.jmir.org/2020/11/e20840}{Paper 1}}, \\textcolor{tdunn-blue}{\\href{https://www.jmir.org/2022/1/e29219}{paper 2}}.)
      \\item Used data simulations to investigate statistical properties of the Goal Attainment Scaling outcome measure. (\\textcolor{tdunn-blue}{\\href{https://github.com/taylordunn/isoqol2021-gas-sim}{Project 1}}, \\textcolor{tdunn-blue}{\\href{https://github.com/taylordunn/ispor-europe2021-gas-sim}{project 2}}.)
      \\item Analyzed neuropsychiatric symptoms reported by over 4000 online users tracking dementia symptoms. (\\textcolor{tdunn-blue}{\\href{https://www.jmir.org/2019/6/e13360/}{Paper}}.)
      \\item Presented public webinars on patient-centric outcomes. (\\textcolor{tdunn-blue}{\\href{https://xtalks.com/webinars/using-goal-attainment-scaling-to-capture-the-patient-voice/}{Xtalks}}, \\textcolor{tdunn-blue}{\\href{https://ardeaoutcomes.com/news/2020/11/ardea-outcomes-launches-goal-attainment-scaling-insights-webinar-series/}{WorkCast}}.)
    \\end{itemize}",
    "Built the R code infrastructure for many data analysis and management activities, saving analysts several hours per week in each project:
    \\begin{itemize}
      \\item Developed internal R package for interfacing with AWS database and transforming raw clinical trials data into clean data sets and reports.
      \\item Developed internal R package for company-branded figures and RMarkdown reporting templates.
      \\item Developed open-source R package for simulating Goal Attainment Scaling data in clinical trials. (\\textcolor{tdunn-blue}{\\href{https://github.com/taylordunn/gasr}{GitHub}}.)
      \\item Developed internal Shiny dashboards and deployed on AWS for live data monitoring.
    \\end{itemize}"),
  "2014-2016", "Teaching Assistant", "Dalhousie University, Department of Physics", "Halifax, NS",
  c("Aided instruction of Physics students in the undergraduate course \\textit{Introduction to Numerical Programming}.",
    "Ran weekly Python tutorial sessions, graded assignments and projects, and gave lectures when professor was absent.")
) %>%
  detailed_entries(
    when = year, with = position, where = location, why = details,
    what = company,
    .protect = FALSE
  )
  
```

# Education

```{r}
tribble(
  ~ degree, ~ year, ~ institution, ~ location,
  "MSc Physics", "2014-2016", "Dalhousie University", "Halifax, NS",
  "BSc Physics, Honours", "2009-2014", "University of Prince Edward Island", "Charlottetown, PE"
) %>% 
  detailed_entries(
    what = degree, when = year, with = institution, where = location
  )
```

# Projects

```{r}
projects <- tribble(
  ~ project, ~ year, ~ description, ~ link,
  "Predicting bike ridership in Halifax, NS", "2022",
  c("An end-to-end machine learning project to predict daily bike ridership in Halifax, Nova Scotia, Canada.",
    "Deployed on Google Cloud Platform as a \\textcolor{tdunn-blue}{\\href{https://hfx-bike-ridership-app-74govvz7xq-uc.a.run.app/}{Shiny dashboard}} and a \\textcolor{tdunn-blue}{\\href{https://hfx-bike-ridership-api-74govvz7xq-uc.a.run.app/__docs__/}{REST API}}.",
    "Wrote about the steps taken in a three part series: \\textcolor{tdunn-blue}{\\href{https://tdunn.ca/posts/2022-04-27-predicting-bike-ridership-getting-the-data/}{retrieving the data}}, \\textcolor{tdunn-blue}{\\href{https://tdunn.ca/posts/2022-04-29-predicting-bike-ridership-developing-a-model/}{developing and evaluating models}}, and \\textcolor{tdunn-blue}{\\href{https://tdunn.ca/posts/2022-05-19-predicting-bike-ridership-deploying-the-model/}{putting the model into production}}."),
  "\\bodyfontlight\\color{tdunn-blue}\\href{https://github.com/taylordunn/hfx-bike-ridership}{https://github.com/taylordunn/hfx-bike-ridership}",
  "Canadian COVID-19 dashboard", "2021",
  c("A dashboard built in Shiny that reports and visualizes the latest COVID-19 numbers in Canada."),
  "\\bodyfontlight\\color{tdunn-blue}\\href{https://taylor-dunn.shinyapps.io/canadacovidshiny/}{https://taylor-dunn.shinyapps.io/canadacovidshiny/}",
  "canadacovid", "2021", "An R package to pull Canadian COVID-19 data from a public API. Published on \\textcolor{tdunn-blue}{\\href{https://cran.r-project.org/web/packages/canadacovid/index.html}{CRAN}}.", "\\bodyfontlight\\color{tdunn-blue}\\href{https://taylordunn.github.io/canadacovid/}{https://taylordunn.github.io/canadacovid/}",
  "TidyTuesday dashboard", "2022", "A dashboard built in Shiny compiling tweets for the \\textcolor{tdunn-blue}{\\href{https://github.com/rfordatascience/tidytuesday}{TidyTuesday data project}.}", "\\bodyfontlight\\color{tdunn-blue}\\href{https://taylor-dunn.shinyapps.io/tidytuesday-dashboard/}{https://taylor-dunn.shinyapps.io/tidytuesday-dashboard/}",
  "dunnr", "2020", "A personal R package of plotting templates and functions that I commonly use.", "\\bodyfontlight\\color{tdunn-blue}\\href{https://github.com/taylordunn/dunnr}{https://github.com/taylordunn/dunnr}"
)
projects %>%
  filter(project != "dunnr") %>%
  detailed_entries(
    with = project, where = NA, why = description,
    what = link, when = year,
    .protect = FALSE
  )
```

# Skills

```{r skills-table, results='markup'}
tribble(
  ~ Programming, ~ Tools, ~ `Data analysis`,
  "R: tidyverse, Shiny, ggplot2, RMarkdown, tidymodels \\newline
  Python: NumPy, Pandas, Seaborn, Scikit-learn \\newline
  SQL -- Bash -- C",
  "Git -- Amazon Web Services \\newline
  Docker -- Google Cloud Platform \\newline
  GitHub Actions -- Mendeley",
  "Generalized linear modeling -- Machine learning \\newline
  Random forest -- Suport-vector machines \\newline
  K-nearest neighbors -- Principal components analysis
  Data simulation -- Visualization -- Data scraping"
) %>%
  kable(booktabs = TRUE, align = 'c', escape = FALSE, format = "latex") %>%
  kable_styling(full_width = FALSE, font_size = 8,
                latex_options = "HOLD_position") %>%
  row_spec(0, bold = TRUE, font_size = 10, underline = FALSE) %>%
  row_spec(1, bold = FALSE) %>%
  column_spec(column = 1, width = "6.3cm") %>%
  column_spec(column = 2, width = "4.0cm") %>%
  column_spec(column = 3, width = "6.4cm") %>%
  # Using regex to remove horizontal lines
  sub("\\\\toprule", "", .) %>%
  sub("\\\\midrule", "", .) %>%
  sub("\\\\bottomrule", "", .)
```

